---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: healthcare-db-pvc
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-db
  template:
    metadata:
      labels:
        app: healthcare-db
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: healthcare-db
          image: mysql:8.0
          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpass
            - name: MYSQL_DATABASE
              value: healthcaredb
            - name: MYSQL_USER
              value: appuser
            - name: MYSQL_PASSWORD
              value: apppass

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 20

          volumeMounts:
            - name: healthcare-db-data
              mountPath: /var/lib/mysql

      volumes:
        - name: healthcare-db-data
          persistentVolumeClaim:
            claimName: healthcare-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-db
spec:
  type: LoadBalancer
  selector:
    app: healthcare-db
  ports:
    - port: 3306
      targetPort: 3306

