apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
      annotations:
        instrumentation.opentelemetry.io/inject-java: "observability/spring-instrumentation"
    spec:
      containers:
        - name: patient-service
          image: sumanth17121988/patient-service:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://healthcare-db.default.svc.cluster.local:3306/healthcaredb
            - name: SPRING_DATASOURCE_USERNAME
              value: appuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: apppass
          volumeMounts:
            - name: config
              mountPath: /config/application.properties
              subPath: application.properties
      volumes:
        - name: config
          configMap:
            name: patient-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  type: LoadBalancer
  selector:
    app: patient-service
  ports:
    - port: 8081
      targetPort: 8081
