# local dev defaults only (will be overridden in Kubernetes)

spring.application.name=patient-service
server.port=8081
spring.datasource.url=jdbc:mysql://${DB_HOST:35.238.70.253}:3306/healthcaredb
spring.datasource.username=${DB_USER:appuser}
spring.datasource.password=${DB_PASS:apppass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
